### PR TITLE
fix NoMethodError: super: no superclass method `destroy' bug

### PR DESCRIPTION
**Pull request by kimsuelim**
Invalid calling super from module method

### CODE REVIEW

**Comment by astjohn** [comment]
:+1: 
@kimsuelim, Thanks for this!

**Comment by schasse** [comment]
+1

**Comment by haihappen** [comment]
Merged, thx :)

**Comment by haihappen** [comment]
Bumped to `1.0.1` with 66036abac79401face4e0f0f708f1bf783f421d8!

**Pull request merged**
